### PR TITLE
Add support for multiple levels of nesting, and fix empty values

### LINKED ISSUE #13: Complex properties are not rendered
**Describe the bug**
Within the properties sub-heading of a selected log message, complex properties are not displayed. The property name is included in the left column, but the right column does not contain any value. Properties that are scalar are rendered appropriately.

**To Reproduce**
1. Create a log file with the following text:
```json
{
  "@t": "2019-12-10T13:33:23.0970926Z",
  "@mt": "An unknown error occurred",
  "@l": "Error",
  "@x": "Exception stack trace",
  "SourceContext": "MySourceContext",
  "Scope": [
    "FirstScope",
    1850562557,
    "198441851"
  ],
  "MachineName": "MY-MACHINE",
  "EnvironmentUserName": "WORKGROUP\\SYSTEM",
  "ExceptionDetail": {
    "HResult": -2146233087,
    "Message": "Internal Error",
    "Source": "System.ServiceModel",
    "Action": null,
    "Code": {
      "IsPredefinedFault": true,
      "IsSenderFault": true,
      "IsReceiverFault": false,
      "Namespace": "http://schemas.xmlsoap.org/soap/envelope/",
      "Name": "Client",
      "SubCode": null
    },
    "Reason": {
      "Translations": [
        {
          "XmlLang": "",
          "Text": "Internal Error"
        }
      ]
    },
    "Type": "System.ServiceModel.FaultException"
  },
  "AssemblyVersion": "2.1.0.1017"
}
```

```json
{"@t":"2019-12-10T13:33:23.0970926Z","@mt":"An unknown error occurred","@l":"Error","@x":"Exception stack trace","SourceContext":"MySourceContext","Scope":["FirstScope",1850562557,"198441851"],"MachineName":"MY-MACHINE","EnvironmentUserName":"WORKGROUP\\SYSTEM","ExceptionDetail":{"HResult":-2146233087,"Message":"Internal Error","Source":"System.ServiceModel","Action":null,"Code":{"IsPredefinedFault":true,"IsSenderFault":true,"IsReceiverFault":false,"Namespace":"http://schemas.xmlsoap.org/soap/envelope/","Name":"Client","SubCode":null},"Reason":{"Translations":[{"XmlLang":"","Text":"Internal Error"}]},"Type":"System.ServiceModel.FaultException"},"AssemblyVersion":"2.1.0.1017"}
```

2. Open this file with Compact Log Viewer
3. Select the (only) log message to expand it
4. See that the properties Scope and ExceptionDetail are empty.

**Expected behavior**
The two complex properties should have values displayed in the right column. Since they are complex properties, a JSON rendering would be applicable.

**Screenshots**
The complex properties are highlighted in yellow. Sensitive data has been scrubbed.
compact-log-viewer-bug

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1803

### LINKED ISSUE #705: Properties that are 0 or false are not shown
**Describe the bug**
Integers with the value 0 and booleans with the value false are shown as empty. 

**To Reproduce**
Load this log file:
`{"@t":"2022-08-22T20:42:37.1929215+02:00","@m":"Test","ZeroInt":0,"FalseBool":false}`

**Expected behavior**
ZeroInt should be shown as "0", and FalseBool should be shown as "false"

**Screenshots**
clef_zero_false

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.3.2.0

### PR DESCRIPTION
**Pull request by EBD232**
Added support for multiple levels of nesting, using recursion. I have attached a sample file, that is shown in the screenshot.

I'm not sure if this totally fixes #13, but it seems to work fine for me. 
Also fixes #705

clef_nesting
[nesting.txt](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/9995987/nesting.txt)

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Code change looks good to me @EBD232 
Do you have a good example JSON log file with nesting to test this out with please ?

**Comment by EBD232** [comment]
Great! There is a nesting.txt attached in the original message above that I used for testing. The .json extension was not allowed as an attached file

**Comment by warrenbuckley** [comment]
Will look at this later tonight or tomorrow. Kid/family stuff now 😄

**Comment by warrenbuckley** [comment]
Tested this out and works lovely - thanks @EBD232 🔥💪🎉 

I tried out your JSON file and another that was originally reported in #13 

## Example JSON files
Rename them to .json from .txt

* [another-nested-log-file.json.txt](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/10260534/another-nested-log-file.json.txt)
* [nesting-log-file.json.txt](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/10260535/nesting-log-file.json.txt)


image

**Pull request merged**
